module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    screens: {
      '2xl': { min: '1200px' },
      '4xl': { max: '1600px' },
      '3xl': { max: '1439px' },
      xl: { max: '1199px' },
      lg: { max: '991px' },
      md: { max: '767px' },
      lsm: { max: '640px' },
      sm: { max: '575px' },
      dateRange: { max: '550px' },
      xsm: { max: '374px' },
    },
    extend: {
      spacing: {
        unset: 'unset',
      },
      colors: {
        primaryColor: 'var(--primaryColor)',
        secondaryColor: 'var(--secondaryColor)',
        primaryColor__hoverDark: 'var(--primaryColor__hoverDark)',
        black__TextColor900: 'var(--black__TextColor900)',
        black__TextColor800: 'var(--black__TextColor800)',
        black__TextColor700: 'var(--black__TextColor700)',
        black__TextColor600: 'var(--black__TextColor600)',
        black__TextColor500: 'var(--black__TextColor500)',
        black__TextColor400: 'var(--black__TextColor400)',
        black__TextColor300: 'var(--black__TextColor300)',
        black__TextColor200: 'var(--black__TextColor200)',
        black__TextColor100: 'var(--black__TextColor100)',
        black__BorderColor900: 'var(--black__TextColor900)',
        black__BorderColor800: 'var(--black__BorderColor800)',
        black__BorderColor700: 'var(--black__BorderColor700)',
        black__BorderColor600: 'var(--black__BorderColor600)',
        black__BorderColor500: 'var(--black__BorderColor500)',
        black__BorderColor400: 'var(--black__BorderColor400)',
        black__BorderColor300: 'var(--black__BorderColor300)',
        black__BorderColor200: 'var(--black__BorderColor200)',
        black__BorderColor100: 'var(--black__BorderColor100)',
        gray__BGColor: 'var(--gray__BGColor)',
        parentBgWhite__grayBtnBG: 'var(--parentBgWhite__grayBtnBG)',
        parentBgGray__grayBtnBG: 'var(--parentBgGray__grayBtnBG)',
        lightScreenBg: 'var(--lightScreenBg)',
        lightScreenDarkBg: 'var(--lightScreenDarkBg)',
        ipWhite__bgColor: 'var(--ipWhite__bgColor)',
        ipBlack__bgColor: 'var(--ipBlack__bgColor)',
        ipWhite__textColor: 'var(--ipWhite__textColor)',
        ipBlack__textColor: 'var(--ipBlack__textColor)',
        ipWhite__borderColor: 'var(--ipWhite__borderColor)',
        ipBlack__borderColor: 'var(--ipBlack__borderColor)',
        primary__transparentBG: 'var(--primary__transparentBG)',
        primaryColor__transparentBG: 'var(--primaryColor__transparentBG)',
        formLabel__blueColor: 'var(--formLabel__blueColor)',

        ip__black__text__color: 'var(--ip__black__text__color)',
        ip__white__text__color: 'var(--ip__white__text__color)',
        dark__TextColor: 'var(--dark__TextColor)',
        mediumDark__TextColor: 'var(--mediumDark__TextColor)',
        light__TextColor: 'var(--light__TextColor)',
        disableLight__TextColor: 'var(--disableLight__TextColor)',
        whiteScreen__BorderColor: 'var(--whiteScreen__BorderColor)',
        greyScreen__BorderColor: 'var(--greyScreen__BorderColor)',
        ip__Blue: 'var(--ip__Blue)',
        ip__Orange: 'var(--ip__Orange)',
        ip__Green: 'var(--ip__Green)',
        ip__SuccessGreen: 'var(--ip__SuccessGreen)',
        ip__Red: 'var(--ip__Red)',
        ip__Yellow: 'var(--ip__Yellow)',
        ipBlue__transparentBG: 'var(--ipBlue__transparentBG)',
        ipOrange__transparentBG: 'var(--ipOrange__transparentBG)',
        ipGreen__transparentBG: 'var(--ipGreen__transparentBG)',
        ipSuccessGreen__transparentBG: 'var(--ipSuccessGreen__transparentBG)',
        ipRed__transparentBG: 'var(--ipRed__transparentBG)',
        ipYellow__transparentBG: 'var(--ipYellow__transparentBG)',
        ipGray__transparentBG: 'var(--ipGray__transparentBG)',
        ipGray__transparentBG__light: 'var(--ipGray__transparentBG__light)',
        ip__Blue__hoverDark: 'var(--ip__Blue__hoverDark)',
        ip__Orange__hoverDark: 'var(--ip__Orange__hoverDark)',
        ip__Green__hoverDark: 'var(--ip__Green__hoverDark)',
        ip__SuccessGreen__hoverDark: 'var(--ip__SuccessGreen__hoverDark)',
        ip__Red__hoverDark: 'var(--ip__Red__hoverDark)',
        ip__Yellow__hoverDark: 'var(--ip__Yellow__hoverDark)',
        ip__Grey__hoverDark: 'var(--ip__Grey__hoverDark)',
        DarkBtn__BGcolor: 'var(--DarkBtn__BGcolor)',
        secondary__Btn__BGColor: 'var(--secondary__Btn__BGColor)',
        secondary__Btn__BGColor__hover: 'var(--secondary__Btn__BGColor__hover)',
        rounded__Btn__BGColor: 'var(--rounded__Btn__BGColor)',
        lightGray__BgColor: 'var(--lightGray__BgColor)',
        formField__BGColor: 'var(--formField__BGColor)',
        skeleton__BoxBG: 'var(--skeleton__BoxBG)',
        badge__primary: 'var(--badge__primary)',
        badge__success: 'var(--badge__success)',
        badge__danger: 'var(--badge__danger)',
        badge__warning: 'var(--badge__warning)',
        badge__orange: 'var(--badge__orange)',
        badge__info: 'var(--badge__info)',
        badge__primary__bg: 'var(--badge__primary__bg)',
        badge__secondary__bg: 'var(--badge__secondary__bg)',
        badge__success__bg: 'var(--badge__success__bg)',
        badge__danger__bg: 'var(--badge__danger__bg)',
        badge__warning__bg: 'var(--badge__warning__bg)',
        badge__orange__bg: 'var(--badge__orange__bg)',
        badge__info__bg: 'var(--badge__info__bg)',
        badge__light__bg: 'var(--badge__light__bg)',
        badge__primaryDark__bg: 'var(--badge__primaryDark__bg)',
        badge__secondaryDark__bg: 'var(--badge__secondaryDark__bg)',
        badge__successDark__bg: 'var(--badge__successDark__bg)',
        badge__dangerDark__bg: 'var(--badge__dangerDark__bg)',
        badge__warningDark__bg: 'var(--badge__warningDark__bg)',
        badge__orangeDark__bg: 'var(--badge__orangeDark__bg)',
        badge__infoDark__bg: 'var(--badge__infoDark__bg)',
        badge__lightDark__bg: 'var(--badge__lightDark__bg)',

        primaryColorNew: 'var(--primaryColorNew)',
        primaryColorNewHover: 'var(--primaryColorNewHover)',

        whiteColor: 'var(--whiteColor)',
        blackColor: 'var(--blackColor)',

        sidebarBg: 'var(--sidebarBg)',
        sidebarLogoutBg: 'var(--sidebarLogoutBg)',
        sidebarLogoTextColor: 'var(--sidebarLogoTextColor)',
        sidebarMenuTextColor: 'var(--sidebarMenuTextColor)',

        primaryColorSD: 'var(--primaryColorSD)',
        sdWhite__text: 'var(--sdWhite__text)',
        sdBlack__text: 'var(--sdBlack__text)',
        sdWhite__border: 'var(--sdWhite__border)',
        sdBlack__border: 'var(--sdBlack__border)',
        sdWhite__bg: 'var(--sdWhite__bg)',
        sdBlack__bg: 'var(--sdBlack__bg)',
        btnGrayColor: 'var(--btnGrayColor)',
        whiteScreenBorderColor: 'var(--whiteScreenBorderColor)',
        sdNormal__textColor: 'var(--sdNormal__textColor)',
        darkTextColorSD: 'var(--darkTextColorSD)',
        mediumDarkTextColorSD: 'var(--mediumDarkTextColorSD)',
        grayIconDarkColor: 'var(--grayIconDarkColor)',
        grayIconLightColor: 'var(--grayIconLightColor)',
        formElementBG: 'var(--formElementBG)',
        lightTextForGrayBG: 'var(--lightTextForGrayBG)',
      },
      fontFamily: {
        ovo: ['Ovo'],
        biotif__Black: ['Biotif-Black'],
        biotif__BlackItalic: ['Biotif-BlackItalic'],
        biotif__Bold: ['Biotif-Bold'],
        biotif__BoldItalic: ['Biotif-BoldItalic'],
        biotif__Book: ['Biotif-Book'],
        biotif__BookItalic: ['Biotif-BookItalic'],
        biotif__ExtraBold: ['Biotif-ExtraBold'],
        biotif__ExtraBoldItalic: ['Biotif-ExtraBoldItalic'],
        biotif__Light: ['Biotif-Light'],
        biotif__LightItalic: ['Biotif-LightItalic'],
        biotif__Medium: ['Biotif-Medium'],
        biotif__MediumItalic: ['Biotif-MediumItalic'],
        biotif__Regular: ['Biotif-Regular'],
        biotif__RegularItalic: ['Biotif-RegularItalic'],
        biotif__SemiBold: ['Biotif-SemiBold'],
        biotif__SemiBoldItalic: ['Biotif-SemiBoldItalic'],
      },
      fontSize: {
        heading36: '36px',
        heading30: '30px',
        heading22: '22px',
        heading18: '18px',
        body14: '14px',
        body12: '12px',
      },
    },
  },
  plugins: [],
};
