export const {
  REACT_APP_URL,
  REACT_APP_FRONT_URL,
  REACT_APP_API_URL,
  REACT_APP_API_BASE_URL,
  SERVER_URL,
  REACT_APP_GOOGLE_CLIENT_ID,
  REACT_APP_FRONT_CMS_URL,
  REACT_APP_GOOGLE_TRANSLATE,
  REACT_APP_GOOGLE_MAPS_ID,
  SENTRY_DNS,
  REACT_APP_GOOGLE_MAP_ENABLED,
} = process.env;
