import { RegisterInitialValueType } from '../../../../../modules/Auth/pages/Register/types';

export const registerInitialValues: RegisterInitialValueType = {
  company_name: '',
  company_vat_number: '',
  company_legal_name: '',
  company_registration_number: '',
  company_accounting_emails: [{ email: '', is_primary: false }],
  company_address_l1: '',
  company_address_l2: '',
  company_address_country: '',
  address_province: '',
  company_address_city: '',
  company_address_zip: '',
  company_website: '',
  company_industry: '',
  company_ateco_code: '',
  company_is_invoice: '',
  company_sdi_code: '',
  company_size: '',
  manager_first_name: '',
  manager_last_name: '',
  manager_job_title: '',
  manager_contact: '',
  manager_email: '',
  manager_address_l1: '',
  manager_address_l2: '',
  manager_address_country: '',
  manager_address_state: '',
  manager_address_city: '',
  manager_address_zip: '',
  company_logo: '',
  company_description: '',
  vat_type: '',
};
